version: '3.8'

services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: soul_linker_db
      MYSQL_USER: soul_linker_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
